"""Add character summary table

Revision ID: 000000000012
Revises: 000000000011
Create Date: 2025-06-16 15:07:27.863519

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "000000000012"
down_revision = "000000000011"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.create_table(
        "chat_configuration_summary",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("chat_configuration_id", sa.UUID(), nullable=False),
        sa.Column("summary", sa.String(), nullable=False),
        sa.Column("last_summarized_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_configuration_id"],
            ["chat_configuration.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chat_configuration_id"),
    )
    # Set all chat_configuration_id-s to the latest chat_configurations user has
    op.execute("""
    UPDATE chat
    SET chat_configuration_id = sub.latest_id
    FROM (
        SELECT DISTINCT ON (user_profile_id)
               id AS latest_id,
               user_profile_id
        FROM chat_configuration
        ORDER BY user_profile_id, id DESC
    ) AS sub
    WHERE chat.user_profile_id = sub.user_profile_id;
    """)
    # Delete all old chat_configurations
    op.execute("""
    DELETE FROM chat_configuration
    WHERE id NOT IN (
        SELECT latest_id FROM (
            SELECT DISTINCT ON (user_profile_id) id AS latest_id
            FROM chat_configuration
            ORDER BY user_profile_id, id DESC
        ) AS latest
    );
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_table("chat_configuration_summary")
    # ### end Alembic commands ###
