"""Add detailed data in UserProfile

Revision ID: 000000000003
Revises: 000000000002
Create Date: 2025-06-12 23:45:29.792279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000000000003'
down_revision = '000000000002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('name', sa.String(), nullable=True))
    op.add_column('user_profile', sa.Column('profile_picture', sa.String(), nullable=True))
    op.add_column('user_profile', sa.Column('auth_provider', sa.String(), nullable=False))
    op.add_column('user_profile', sa.Column('provider_id', sa.String(), nullable=False))
    op.add_column('user_profile', sa.Column('is_email_verified', sa.Boolean(), nullable=False))
    op.add_column('user_profile', sa.Column('last_login_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'last_login_at')
    op.drop_column('user_profile', 'is_email_verified')
    op.drop_column('user_profile', 'provider_id')
    op.drop_column('user_profile', 'auth_provider')
    op.drop_column('user_profile', 'profile_picture')
    op.drop_column('user_profile', 'name')
    # ### end Alembic commands ###
