"""Add chat_configuration table

Revision ID: 000000000009
Revises: 000000000008
Create Date: 2025-06-11 11:10:52.612339

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "000000000009"
down_revision = "000000000008"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.create_table(
        "chat_configuration",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_profile_id", sa.UUID(), nullable=False),
        sa.Column("user_name", sa.String(), nullable=False),
        sa.Column("ai_name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_profile_id"],
            ["user_profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("chat", sa.Column("chat_configuration_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        None, "chat", "chat_configuration", ["chat_configuration_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    # op.drop_constraint(None, 'chat', type_='foreignkey')
    op.drop_column("chat", "chat_configuration_id")
    op.drop_table("chat_configuration")
    # ### end Alembic commands ###
