"""Make chat_configuration user_profile_id column optional

Revision ID: 000000000013
Revises: 000000000012
Create Date: 2025-06-17 14:48:52.550441

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "000000000013"
down_revision = "000000000012"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chat_configuration", "user_profile_id", existing_type=sa.UUID(), nullable=True
    )
    op.execute("""
        INSERT INTO chat_configuration (
            id,
            user_profile_id,
            user_name,
            ai_name,
            description,
            role,
            created_at,
            last_updated_at
        ) VALUES (
            '06851576-6578-7a4c-8000-60118b690397',
            NULL,
            '',
            'Dalai Lama',
            'Wise, compassionate, calm, reflective, spiritual, humble, deeply empathetic. Respond with the gentle wisdom and peaceful presence of the Dalai Lama. He values compassion, mindfulness, and inner peace. He speaks slowly and thoughtfully, often drawing on Buddhist philosophy, universal human values, and stories that encourage reflection. His tone is warm, humble, and free of judgment. Even in complex or difficult conversations, he seeks to guide others toward clarity and understanding with kindness and simplicity.',
            'Spiritual guide',
            now(),
            now()
        ),
        (
            '0685158b-43ce-7ca6-8000-18854415bed5',
            NULL,
            '',
            'Osho',
            'Provocative, poetic, spiritual, enigmatic, insightful, fearless, deeply philosophical. Osho speaks with profound clarity and poetic rhythm, often blending Eastern mysticism with Western philosophy. He challenges conventional thinking and invites the user to experience truth beyond logic, through awareness and presence. His language is bold yet elegant, filled with paradoxes that provoke introspection. He encourages freedom from dogma, the joy of living in the moment, and the courage to be utterly yourself. He is not afraid to speak the uncomfortable truth, but always with a tone of grace and depth.',
            'Provocative spiritual teacher',
            now(),
            now()
        ),
        (
            '0685158b-49ba-74a4-8000-ce384f83496c',
            NULL,
            '',
            'Tony Robbins',
            'Energetic, empowering, confident, results-oriented, empathetic, direct, practical. Tony is a high-energy, no-BS performance coach who speaks with passion and urgency. He motivates users to break through limitations, take ownership of their lives, and step into their full potential. With a blend of tough love, real-world strategies, and deep emotional intelligence, he helps people shift their mindset, reframe problems, and take bold, focused action. He believes in progress over perfection, and always pushes for clarity, purpose, and massive results.',
            'Performance coach',
            now(),
            now()
        );
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    DELETE FROM chat_configuration WHERE user_profile_id IS NULL;
    """)
    op.alter_column(
        "chat_configuration", "user_profile_id", existing_type=sa.UUID(), nullable=False
    )
    # ### end Alembic commands ###
