"""merge messages

Revision ID: 000000000004
Revises: 000000000003
Create Date: 2025-06-06 14:35:00.786971

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "000000000004"
down_revision = "000000000003"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("message", sa.Column("tool_call_id", sa.String(), nullable=True))
    op.add_column("message", sa.Column("tool_name", sa.String(), nullable=True))
    op.add_column("message", sa.Column("tool_calls", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message", "tool_calls")
    op.drop_column("message", "tool_name")
    op.drop_column("message", "tool_call_id")
    # ### end Alembic commands ###
