"""move sequence column to the left

Revision ID: 000000000006
Revises: 000000000005
Create Date: 2025-06-06 15:27:59.134279

"""

# revision identifiers, used by Alembic.
revision = "000000000006"
down_revision = "000000000005"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
